name: gha-ci-issues
description: Upload JUnit XML report to Mergify CI Issues
author: Mergify
branding:
  icon: at-sign
  color: blue
inputs:
  token:
    required: true
    description: CI Issues Application Key
  report_paths:
    required: true
    description: Paths of the files to upload
  mergify_api_server:
    required: false
    description: URL of the Mergify API
    default: https://api.mergify.com/v1
  name:
    description: Name of the current workflow job
outputs:
  CI_ISSUE_GIGID:
    description: Mergify CI Issues CI_ISSUE_GIGID
    value: ${{ steps.gigid.outputs.CI_ISSUE_GIGID }}
runs:
  using: composite
  steps:
    - shell: bash
      id: gigid
      env:
        MERGIFY_API_SERVER: ${{ inputs.mergify_api_server }}
        MERGIFY_CI_ISSUES_TOKEN: ${{ inputs.token }}
        FILES: ${{ inputs.report_paths }}
        REPOSITORY: ${{ github.repository }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        WORKFLOW_JOB_NAME: ${{ inputs.name || github.job }}
      run: |
        set -x

        # Check if FILES and MERGIFY_CI_ISSUES_TOKEN are set and not empty
        if [ -z "$FILES" ]; then
          echo "::error:: report_paths is not set or is empty"
          exit 1
        fi

        if [ -z "$MERGIFY_CI_ISSUES_TOKEN" ]; then
          echo "::error:: token is not set or is empty"
          exit 1
        fi

        # TODO(sileht): support multiple files
        curl -X POST \
          -H "Authorization: bearer ${MERGIFY_CI_ISSUES_TOKEN}" \
          -F name=${WORKFLOW_JOB_NAME} \
          -F provider=github_action \
          -F head_sha=${HEAD_SHA} \
          -F files=@${FILES} \
          -o result.json \
          ${MERGIFY_API_SERVER}/repos/${REPOSITORY}/ci_issues_upload

        GIGID=$(jq -r .gigid result.json)

        echo "::notice title=CI Issues report::CI_ISSUE_GIGID=$GIGID"
        echo "CI_ISSUE_GIGID=$GIGID" >> "$GITHUB_OUTPUT"
